# Generated by Django 5.2.4 on 2025-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusapp', '0003_assignment_assignmentsubmission_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
