# Generated by Django 5.2.4 on 2025-07-21 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusapp', '0004_alter_assignmentsubmission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='department_name',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='dep_name', to='campusapp.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('resource_file', models.FileField(upload_to='resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusapp.subjectlist')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusapp.faculty')),
            ],
        ),
    ]
